openapi: 3.0.1
info:
  title: Portal Providers API
  description: |
    ## Overview
    An API Provider has the privileges to enable an API Portal Administrator or Provider to manage
    APIs, and configure notification types that are used for API-related events.

    There are two types of API providers in API Portal:

    ### Default Provider
      Any API that is imported and not associated with any other API provider
      is automatically associated with the Default Provider.
      When an imported API is associated with a new API provider, it gets disassociated from the Default Provider.

    ### External Provider
      Any other provider falls under this category

    ## Functionalities supported
    - Create,Update,Delete and Retieve API Providers.
    - Link/UnLink APIs to the Provider
    - Retrieve APIs linked to the Provider
    - Link/UnLink Packages to the Provider
    - Retrieve Packages linked to the Provider

    ## Authorization
    - Users with role 'Administrator' and/or 'Provider' can create/modify/delete a provider, link/unlink APIs to a provider, link/unlink packages to a provider
    - Users with role 'Administrator' and/or 'Provider' and/or 'Consumer' can view list of available providers, APIs/Packages linked with the provider.

  version: "10.11"

servers:
  - url: http://localhost:18101/portal/rest/v1
    description: Development server

paths:
  '/providers':
    get:
      tags:
        - "Provider"
      summary: Retrieves the list of providers
      responses:
        '200':
          $ref: '#/components/responses/SearchResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

      parameters:
        - name: page
          in: query
          description: Optional parameter. Defines the page number to be retrieved for the collection.If not specified default value 0 is assumed. By default collection responses are paginated with batches of 10.
          required: false
          schema:
            type: integer

        - name: limit
          in: query
          description: Optional parameter. Defines the number of results to be fetched for the current page. If not specified default value configured in system settings will be considered.
          required: false
          schema:
            type: integer


    post:
      tags:
        - "Provider"
      summary: Create/Publish a new provider
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIProviderDTO'
            examples:
              APIProviderDTO:
                $ref: '#/components/examples/APIProviderDTO'
      responses:
        '201':
          $ref: '#/components/responses/CreationResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  '/providers/{id}':
    get:
      tags:
        - "Provider"
      summary: Retrieves a provider identified by given id
      parameters: [ ]
      responses:
        '200':
          $ref: '#/components/responses/ProviderResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags:
        - "Provider"
      summary: Updates a provider identified by given id
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIProviderDTO'
            examples:
              APIProviderDTO:
                $ref: '#/components/examples/APIProviderDTO'
      responses:
        '200':
          $ref: '#/components/responses/ProviderResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - "Provider"
      summary: Deletes a provider identified by given id
      parameters: [ ]
      responses:
        '204':
          description: Provider is deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    parameters:
      - name: id
        in: path
        description: Unique identification for provider. Refers to the GUID of the provider.For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
        required: true
        allowEmptyValue: false
        schema:
          type: string
          format: uuid

  '/providers/{id}/apis':
    get:
      tags:
        - "Provider"
      summary: Retrieves list of APIs of provider
      parameters:
        - name: page
          in: query
          description: Optional parameter. Defines the page number to be retrieved for the collection. If not specified default value 0 is assumed.By default collection responses are paginated with batches of 10.
          required: false
          schema:
            type: integer

        - name: limit
          in: query
          description: Optional parameter. Defines the number of results to be fetched for the current page. If not specified default value configured in system settings will be considered.
          required: false
          schema:
            type: integer

        - name: id
          in: path
          description: Unique identification for provider. Refers to the GUID of the provider.For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
          required: true
          allowEmptyValue: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/LinkedAPIResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags:
        - "Provider"
      summary: Link the API to the API Provider
      responses:
        '200':
          $ref: '#/components/responses/LinkAPIResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - "Provider"
      summary: Unlink the API from the API Provider
      parameters: [ ]
      responses:
        '200':
          $ref: '#/components/responses/UnLinkAPIResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    parameters:
      - name: id
        in: path
        description: Unique identification for provider. Refers to the GUID of the provider. For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
        required: true
        allowEmptyValue: false
        schema:
          type: string
          format: uuid


  '/providers/{id}/packages':
    get:
      tags:
        - "Provider"
      summary: Retrieves list of packages of provider
      parameters:
        - name: page
          in: query
          description: Optional parameter. Defines the page number to be retrieved for the collection. If not specified default value 0 is assumed.By default collection responses are paginated with batches of 10.
          required: false
          schema:
            type: integer

        - name: limit
          in: query
          description: Optional parameter. Defines the number of results to be fetched for the current page. If not specified default value configured in system settings will be considered.
          required: false
          schema:
            type: integer

        - name: id
          in: path
          description: Unique identification of provider. Refers to the GUID of the provider.For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
          required: true
          allowEmptyValue: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/LinkedPackageResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags:
        - "Provider"
      summary: Link the packages to the API Provider
      description: Link the existing packages to the API Provider. This operation is allowed only for third party providers.
      responses:
        '200':
          $ref: '#/components/responses/LinkPackageResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'


    delete:
      tags:
        - "Provider"
      summary: Unlink the packages from the API Provider
      description: Unlink the existing packages from the API Provider. This operation is allowed only for third party providers.
      parameters: [ ]
      responses:
        '200':
          $ref: '#/components/responses/UnLinkPackageResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    parameters:
      - name: id
        in: path
        description: Unique identification of provider. Refers to the GUID of the provider. For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
        required: true
        allowEmptyValue: false
        schema:
          type: string
          format: uuid

components:
  securitySchemes:
    accesstoken:
      type: apiKey
      in: cookie
      name: accesstoken
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    ProviderResponse:
      description: Provider response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProviderDto'
          examples:
            APIProvider:
              $ref: '#/components/examples/ProviderDto'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            401:
              $ref: '#/components/examples/401'

    LinkedAPIResponse:
      description: Response while retrieving APIs linked with the provider
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APISummary'
          examples:
            APISummary:
              $ref: '#/components/examples/APISummary'

    LinkAPIResponse:
      description: Link Api Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdationResponse'
          examples:
            LinkAPIExample:
              $ref: '#/components/examples/LinkAPIExample'

    UnLinkAPIResponse:
      description: UnLink Api Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdationResponse'
          examples:
            UnLinkAPIExample:
              $ref: '#/components/examples/UnLinkAPIExample'

    LinkedPackageResponse:
      description: Response while retrieving packages linked with the provider
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PackageSearchResponse'
          examples:
            PackageSummary:
              $ref: '#/components/examples/PackageSummary'

    LinkPackageResponse:
      description: Link Packages Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdationResponse'
          examples:
            LinkPackageExample:
              $ref: '#/components/examples/LinkPackageExample'

    UnLinkPackageResponse:
      description: UnLink Packages Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdationResponse'
          examples:
            UnLinkPackageExample:
              $ref: '#/components/examples/UnLinkPackageExample'

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            403:
              $ref: '#/components/examples/403'
    NotFound:
      description: Provider not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            404:
              $ref: '#/components/examples/404'

    SearchResponse:
      description: Response while retrieving the list of providers in the system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchResponse'
          examples:
            SearchResponse:
              $ref: '#/components/examples/SearchResponse'

    CreationResponse:
      description: The response when provider is created successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedResponse'
          examples:
            CreationResponse:
              $ref: '#/components/examples/CreatedResponse'

  schemas:
    SearchResponse:
      type: object
      properties:
        result:
          type: array
          description: Result list
          items:
            $ref: '#/components/schemas/APIProvider'
        count:
          description: Total number of results found
          type: integer
        _links:
          type: object
          description: Links of current and next page
          required:
            - _self
          properties:
            _self:
              description: Link of current page
              type: string
            _next:
              description: Link of next page
              type: string

    ProviderDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/APIProvider'
      properties:
        hooks:
          type: array
          items:
            $ref: '#/components/schemas/WebHook'
    WebHook:
      type: object
      properties:
        id:
          type: string
          description: Unique identification for webhook. Refers to the GUID of the webhook.For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
        url:
          type: string
          description: Webhook URL to post
        subscriptions:
          type: array
          description: List of events that we want to subscribe to
          items:
            $ref: '#/components/schemas/EventType'
        configuration_type:
          type: string
          description: Indicates whether the webhook is related to system or stage
          enum:
            - "SYSTEM"
            - "PROVIDER"
          default: SYSTEM
        parameters:
          type: object
          description: Parameters of the webhook
          oneOf:
            - $ref: '#/components/schemas/BasicAuthParameter'
            - $ref: '#/components/schemas/SslAuthParameter'
            - $ref: '#/components/schemas/NoAuthParameter'
    EventType:
      description: Type of the event
      type: object
      properties:
        id:
          type: string
          description: Unique identification for event. Refers to the GUID of the event.For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
          enum:
            - API_PUBLISH_EVENT
            - API_REPUBLISH_EVENT
            - API_UN_PUBLISH_EVENT
            - PROVIDER_PUBLISH_EVENT
            - PROVIDER_REPUBLISH_EVENT
            - PROVIDER_UNPUBLISH_EVENT
            - SIGN_UP_EVENT
            - APPLICATION_REQUEST_EVENT
            - APPLICATION_CREATION_REQUEST_EVENT
            - APPLICATION_REQUEST_APPROVED_EVENT
            - APPLICATION_REQUEST_REJECTED_EVENT
            - COMMUNITY_CREATION_EVENT
            - COMMUNITY_DELETION_EVENT
            - COMMUNITY_MEMBERSHIP_CHANGE_EVENT
            - COMMUNITY_SCOPE_CHANGE_EVENT
            - IN_APP_NOTIFICATION_EVENT
            - EMAIL_NOTIFICATION_EVENT
        name:
          type: string
          description: Event name
        description:
          type: string
          description: Event description
    BasicAuthParameter:
      type: object
      allOf:
        - $ref: '#/components/schemas/WebHookParameter'
      properties:
        username:
          type: string
          description: User name to authenticate
        password:
          type: string
          description: Password of the user
    SslAuthParameter:
      type: object
      allOf:
        - $ref: '#/components/schemas/WebHookParameter'
      properties:
        type:
          type: string
          description: Type of certificate used to authenticate with the webhook
        password:
          type: string
          description: Password of the certificate
        file_id:
          type: string
          description: The certificate should be uploaded into API Portal using the File API. This id refer to the certificate file id in the system
    NoAuthParameter:
      type: object
      allOf:
        - $ref: '#/components/schemas/WebHookParameter'
    WebHookParameter:
      type: object
      required:
        - authentication
      properties:
        authentication:
          type: string
      discriminator:
        propertyName: authentication
    APIProvider:
      type: object
      properties:
        id:
          type: string
          description: Unique identification of the provider. Refers to the GUID of the provider. For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
        name:
          type: string
          description: Name of the provider
        description:
          type: string
          description: Description of the provider
        modified:
          type: string
          format: yyyy-MM-dd HH:mm
          description: Modified date
        created:
          type: string
          format: yyyy-MM-dd HH:mm
          description: Created date
        externalRefKey:
          description: External id of the provider
          type: string
        providerurl:
          type: string
          description: Callback url of the provider
        stage:
          type: string
          description: Environment or stage name
        webhooks:
          description: Callback urls of the provider
          type: array
          items:
            type: string
        type:
          description: Type of the provider
          type: string
          enum:
            - "GATEWAY"
            - "CENTRASITE"
            - "THIRD_PARTY"

    APIProviderDTO:
      type: object
      properties:
        id:
          type: string
          description: Unique identification of the provider. Refers to the GUID of the provider. For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
        name:
          type: string
          description: Name of the provider
        description:
          type: string
          description: Description of the provider
        modified:
          type: string
          format: yyyy-MM-dd HH:mm
          description: Modified date
        created:
          type: string
          format: yyyy-MM-dd HH:mm
          description: Created date
        external_key_provider:
          description: External id of the provider
          type: boolean
        version:
          type: string
          description: Version number
        credentials:
          type: string
          description: Credentials

    APISearchResponse:
      required:
        - result
        - count
      type: object
      properties:
        result:
          type: array
          description: Collection of APIs
          items:
            $ref: '#/components/schemas/APISummary'
        _links:
          $ref: '#/components/schemas/Pagination'
        count:
          type: integer
          description: Total number of results found
          format: int32

    PackageSearchResponse:
      required:
        - result
        - count
      type: object
      properties:
        result:
          type: array
          description: Collection of APIs
          items:
            $ref: '#/components/schemas/Package'
        _links:
          $ref: '#/components/schemas/Pagination'
        count:
          type: integer
          description: Total number of results found
          format: int32

    Package:
      type: object
      properties:
        plans:
          description: Plans included in the package
          type: array
          items:
            type: string
            description: Id of the plan
        name:
          type: string
          description: Name of the package
        description:
          type: string
          description: Detailed description and usage of the package
        summary:
          type: string
          description: Short summary of the package
        icon:
          $ref: '#/components/schemas/Icon'
        id:
          type: string
          description: Unique identification of package. Refers to the GUID of the package. For example `532e53ef-3b2a-45af-b859-2456dca1bb1f`
        rating:
          type: number
          description: Review rating of the package for out of 5. Default value is '0'
        communities:
          description: Package shared to the communities
          type: array
          items:
            type: string
            description: Id of the coomunity
        apis:
          description: APIs included in the package
          type: array
          items:
            type: string
            description: Id of the API
        follower:
          type: boolean
          description: Indicates if any follower(s) following the package

    APISummary:
      type: object
      properties:
        id:
          description: Unique identification of API. Refers to the GUID of the API. For example `d4a6bc0b-24dd-4035-862a-0f8f7608512e`
          type: string
          format: uuid
        name:
          type: string
          description: Name of the API
        summary:
          type: string
          description: Summary description for the API
        icon:
          $ref: '#/components/schemas/Icon'
        version:
          type: string
          description: Version number of the API
        type:
          type: string
          description: Type of the API. Indicating REST/SOAP/OData
        externalRefKey:
          type: string
          description: External reference key. Refers to the GUID of the API in the external system like Gateway.

    Icon:
      type: object
      properties:
        url:
          type: string
          description: Uri location for the icon
        type:
          type: string
          description: Type of uri location. refers to either Internal/External. When points to Internal uri is hosted by the API Portal

    Pagination:
      required:
        - _self
      type: object
      properties:
        _self:
          type: string
          description: Link for current page
        _next:
          type: string
          description: Optional link for the next page. Will be missing if the next page does not exist.
    Error:
      type: object
      properties:
        code:
          description: Error code
          type: integer
        message:
          description: Error message
          type: string

    UpdationResponse:
      type: object
      properties:
        code:
          description: Response code
          type: integer
        message:
          description: Response message
          type: string

    CreatedResponse:
      type: object
      properties:
        id:
          description: Identifier of the newly created topic
          type: string
        _self:
          description: Self reference of the newly created topic
          type: string

  examples:
    SearchResponse:
      value:
        result:
          - name: gateway
            owner: 200ceb26-807d-3bf9-9fd6-f4f0d1ca54d4
            id: b9402476-c638-46a5-9779-665fc415a90f
            providerRef: b9402476-c638-46a5-9779-665fc415a90f
            providerurl: http://providerurl:5555
            stage: gateway
            webhooks:
              - b90d20e3-f2c9-4455-8e62-ce989fb34f89
            type: GATEWAY
            externalRefKey: cb4f4e9b-35c4-470a-8d21-48e23b8f2f44
        count: 1
        _links:
          _self: "/rest/v1/providers/?page=0"

    APIProvider:
      value:
        name: Prod Provider
        owner: 200ceb26-807d-3bf9-9fd6-f4f0d1ca54d4
        id: 912ca846-1dd3-416c-b59e-f797a026d26b
        providerRef: 912ca846-1dd3-416c-b59e-f797a026d26b
        stage: Prod
        webhooks:
          - 77d5fa53-b28d-492d-9887-2694507d6f9b
        type: GATEWAY
        summary: desc

    ProviderDto:
      value:
        name: Prod Provider
        owner: 200ceb26-807d-3bf9-9fd6-f4f0d1ca54d4
        id: 912ca846-1dd3-416c-b59e-f797a026d26b
        providerRef: 912ca846-1dd3-416c-b59e-f797a026d26b
        stage: Prod
        type: GATEWAY
        summary: desc
        webhooks:
          - 77d5fa53-b28d-492d-9887-2694507d6f9b
        hooks:
          - id: 77d5fa53-b28d-492d-9887-2694507d6f9b
            url: http://api-dev.xyz.com/rest/apigateway/accesstokens
            subscriptions:
              - id: GATEWAY_APPLICATION_UPDATION_REQUEST_EVENT
                name: Event name
                description: Event description
            enabled: true
            configuration_type: PROVIDER
    APIProviderDTO:
      value:
        name: Provider1
        version: '10.11'
        external_key_provider: false
        shortDescription: desc
        credentials: QWRtaW5pc3RyYXRvcjptYW5hZ2U=
        notificationPlugins:
          - id: HTTP
            pluginParameters:
              com.aris.umc.apiportal.external.event.notify.endpoint: 'http://notification-endpoint:5655/rest'
              com.aris.umc.apiportal.external.event.notify.method: POST
              com.aris.umc.apiportal.external.event.notify.contentType: application/json

    APISummary:
      value:
        result:
          - id: a1264eff-87f9-4e6d-b4b8-abf51855afda
            name: pet1
            summary: 'This is a sample server Petstore server. '
            icon:
              url: "/public/assets/images/rest-api-icon.svg"
              type: INTERNAL
            version: 1.0.5
            type: REST
            externalRefKey: 7f4adf29-3beb-45ef-8c1a-345a8eada6f3
        count: 1
        _links:
          _self: "/rest/v1/providers/3bdf8005-5685-3ef5-b132-de4681963fb6/apis?page=0"

    PackageSummary:
      value:
        result:
          - id: a1264eff-87f9-4e6d-b4b8-abf51855afda
            name: TravelPackage
            summary: 'This is a travel package which includes the APIs related to travel '
            icon:
              url: "/rest/v1/files/9ab59a45-05bb-4781-ace1-bb41675ba867"
              type: INTERNAL
            externalRefKey: 7f4adf29-3beb-45ef-8c1a-345a8eada6f3
        count: 1
        _links:
          _self: "/rest/v1/providers/3bdf8005-5685-3ef5-b132-de4681963fb6/packages?page=0"

    CreatedResponse:
      value:
        id: 4ba06f7c-f4dd-4868-9d97-27134e102d00
        _self: /rest/v1/providers/4ba06f7c-f4dd-4868-9d97-27134e102d00


    LinkAPIExample:
      value:
        code: 200
        message: API/s  linked successfully with provider

    UnLinkAPIExample:
      value:
        code: 200
        message: API/s  un-linked successfully with provider

    LinkPackageExample:
      value:
        code: 200
        message: Package/s  linked successfully with provider

    UnLinkPackageExample:
      value:
        code: 200
        message: Package/s  un-linked successfully with provider

    401:
      value:
        code: 401
        message: "Invalid credentials"

    403:
      value:
        code: 403
        message: "Insufficient privileges"

    404:
      value:
        code: 404
        message: "Unable to find the Provider with id [c234ec5e-8e8d-4e2d-84f1-526b590bfd37]"

security:
  - accesstoken: [ ]
  - bearerAuth: [ ]
